#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# SPDX-FileCopyrightText: Copyright (c) 2026 SoftAtHome
#
# Script to mount prpl securestore partition under /cfg

mount_cfg() {
    CFG_MOUNT="/cfg"
    PRPL_SFL_SECURESTORE_LABEL="securestore"

    if [ ! -d "${CFG_MOUNT}" ]; then
        echo "ERROR: mount point ${CFG_MOUNT} does not exist"
        return 1
    fi

    # Other preinit scripts may have mounted it before this script runs
    if grep -qs " on ${CFG_MOUNT} " /proc/mounts; then
        return 0
    fi

    SECURESTORE_DEV=$(blkid -L ${PRPL_SFL_SECURESTORE_LABEL})

    if [ -z "${SECURESTORE_DEV}" ]; then
        echo "ERROR: ${PRPL_SFL_SECURESTORE_LABEL} partition not found"
        return 1
    fi

    mount -o rw,noatime,nodev,noexec,nosuid ${SECURESTORE_DEV} ${CFG_MOUNT}

    if [ $? -ne 0 ]; then
        echo "ERROR: failed to mount ${PRPL_SFL_SECURESTORE_LABEL} partition"
        return 1
    fi

    echo "${PRPL_SFL_SECURESTORE_LABEL} partition has been mounted on ${CFG_MOUNT}"
}

boot_hook_add preinit_main mount_cfg
