#!/bin/sh

for INITSCRIPT in netdev_cfg.sh mxl-network-init; do
    if [[ -f "$IPKG_INSTROOT/etc/init.d/$INITSCRIPT" ]]; then
        "${SHELL:-sh}" "$IPKG_INSTROOT/etc/rc.common" "$IPKG_INSTROOT/etc/init.d/$INITSCRIPT" disable
        rm -f "$IPKG_INSTROOT/etc/init.d/$INITSCRIPT"
    fi
done

exit 0

