define Package/$(PKG_NAME)-mock
  CATEGORY:=ambiorix
  SUBMENU:=Modules
  TITLE:=$(SHORT_DESCRIPTION) mock
  URL:=https://gitlab.com/prpl-foundation/components/core/modules/mod-xpon-prpl
  DEPENDS += $(PKG_NAME)
endef

define Package/$(PKG_NAME)-mock/description
	xpon prpl module mock
endef

define Package/$(PKG_NAME)-mock/install
	$(INSTALL_DIR) $(1)/opt/prplos/usr/bin
	$(CP) $(PKG_BUILD_DIR)/test_interactive/onu_hal_mock/onu_hal_mock/src/onu_hal_mock $(1)/opt/prplos/usr/bin/xpon-onu-hal-mock
	$(CP) $(PKG_BUILD_DIR)/test_interactive/onu_hal_mock/dbgtool/src/dbgtool $(1)/opt/prplos/usr/bin/xpon-onu-hal-mock-dbgtool
endef

$(eval $(call BuildPackage,$(PKG_NAME)-mock))
