#!/bin/sh /etc/rc.common

START=25
STOP=02
USE_PROCD=1

PROG=/usr/bin/obuspa
CONFIGURATION=obuspa

RESET_FILE="/etc/config/obuspa_param_reset.txt"
SQL_DB_FILE="/etc/obuspa.db"

DEVICE_KEY_CERT="Security.Certificate.2."
CA_BUNDLE="Security.CABundle.1."

get_ca_bundle_file_path() {
    BUNDLE_URI=$(ba-cli -l "${1}CAFile()" | grep "CAFile = " | cut -d '"' -f2)
    echo ${BUNDLE_URI#file://}
}

get_certificate_path() {
    FILE_URI=$(ba-cli -l "${1}.GetCertificateURI()" | grep "CertificateURI = " | cut -d '"' -f2)
    echo ${FILE_URI#file://}
}

get_private_key_uri() {
	ba-cli -l "${1}.GetCertificateURI()" | grep "PrivateKeyURI = " | cut -d '"' -f2
}

register_service()
{
	procd_open_instance ${CONFIGURATION}
	procd_set_param command ${PROG}

	procd_set_param stdout 1
	procd_set_param stderr 1

	count=0
	while [ "$count" -lt 10 ] && [ -z "$CA_FILE" ]; do
		CA_FILE=$(get_ca_bundle_file_path "${CA_BUNDLE}")
		echo "CA_FILE: $CA_FILE"
		if [ -z "$CA_FILE" ]; then
			echo "Waiting for CA_FILE ($count)"
			sleep 1
		fi
		count=$((count + 1))
	done

	CertificateURI=$(get_certificate_path ${DEVICE_KEY_CERT})
	PrivateKeyURI=$(get_private_key_uri ${DEVICE_KEY_CERT})

	echo "CertificateURI=${CertificateURI}"
	echo "PrivateKeyURI=${PrivateKeyURI}"

	boardserial=$(source /etc/environment 2>/dev/null ; echo $SERIALNUMBER)
	boardoui=$(source /etc/environment 2>/dev/null ; echo $MANUFACTUREROUI)
	procd_set_param env USP_BOARD_SERIAL="${boardserial}" \
						USP_BOARD_OUI="${boardoui}" \
						CertificateURI="${CertificateURI}" \
						PrivateKeyURI="${PrivateKeyURI}"

	# -p Enables trace logging of the USP protocol messages. Enable setting -p option to utilize prototracing
	# procd_append_param command -p

	# Log to /var/log/obuspa instead of syslog
	# procd_append_param command -l /var/log/obuspa

	# -v Sets the debug verbosity log level: 0=Off, 1=Error(default), 2=Warning, 3=Info
	procd_append_param command -v 2
	if [ -f "${CA_FILE}" ]; then
		procd_append_param command -t ${CA_FILE}
	fi
	procd_append_param command -r ${RESET_FILE} -f ${SQL_DB_FILE}
	procd_set_param respawn \
			"${respawn_threshold:-10}" \
			"${respawn_timeout:-10}" "${respawn_retry:-5}"

	procd_close_instance
}

start_service() {
	mkdir -p /var/run/usp/
	register_service
}

stop_service() {
	${PROG} -c stop >/dev/null 2>&1
}

reload_service() {
	stop
	start update
}
