#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# SPDX-FileCopyrightText: Copyright (c) 2026 SoftAtHome
#
# Script to mount prpl securestore partition under /cfg

START=15
USE_PROCD=1

CFG_MOUNT="/cfg"
PRPL_SFL_SECURESTORE_LABEL="securestore"

start_service() {

    SECURESTORE_DEV=$(blkid -L ${PRPL_SFL_SECURESTORE_LABEL})

    if [ -z "${SECURESTORE_DEV}" ]; then
        echo "ERROR: ${PRPL_SFL_SECURESTORE_LABEL} partition not found"
        return 1
    fi

    if [ -d "${CFG_MOUNT}" ]; then
        echo "ERROR: mount point ${CFG_MOUNT} does not exist"
        return 1
    fi

    mount -o rw,noatime,nodev,noexec,nosuid ${SECURESTORE_DEV} ${CFG_MOUNT}

    if [ $? -ne 0 ]; then
        echo "ERROR: failed to mount securestore"
        return 1
    fi

    echo "securestore mounted on ${CFG_MOUNT}"
}
